### ISSUE TITLE
Broken memerator.me link.

### ISSUE THREAD

**Issue by John-Paul-R** [Chew/Chew#3]
The link to memerator.me on [projects/memerator.md](https://github.com/Chew/Chew/blob/master/projects/memerator.md) does not include a scheme, so GitHub assumes it is an internal link.

To fix, simply change the line from this:
```
### [Memerator.me](Memerator.me)
```
to this:
```
### [Memerator.me](https://Memerator.me)
```
Example:
### [Memerator.me](https://Memerator.me)

**Comment by Chew** [comment]
Huh, not sure how I missed this in testing
